import { FutbinSearchResultsRowStats } from './types.js'

export const defaultFutbinSearchResultsRowStats: FutbinSearchResultsRowStats = {
  playerFutbinUrl: null,
  playerFutbinId: null,
  firstName: null,
  lastName: null,
  clubName: null,
  nationName: null,
  leagueName: null,
  rating: null,
  preferredPosition: null,
  alternativePositions: null,
  revision: null,
  accelerationType: null,
  price: null,
  skillMovesLevel: null,
  weakFootLevel: null,
  workRates: null,
  pace: null,
  shooting: null,
  passing: null,
  dribbling: null,
  defending: null,
  physicality: null,
  height: null,
  bodyType: null,
  weight: null,
}
